stages:
  - build
  - test
  - deploy

services:
  - docker:dind

before_script:
  - echo "Logging into GitLab Docker registry"
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

Build_frontend:
  image: docker:20.10.7
  stage: build
  script:
    - echo "Building Docker image"
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG -f DockerBuildFrontend .
    - echo "Pushing Docker image to registry"
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

Lint_frontend:
  image: docker:20.10.7
  stage: test
  only:
    refs:
      - merge_requests
  allow_failure: true
  script:
    - echo "Running eslint"
    - docker build --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG -f DockerLint .
    - docker run --rm $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG -f DockerLint
    - docker rmi $CI_JOB_ID
