nodeLinker: node-modules

npmScopes:
  registry:
    npmRegistryServer: "https://registry.yarnpkg.com"
    corepackRegistryServer: "https://corepack.pnpjs.org"

yarnPath: "./.yarn/releases/yarn-berry.cjs"